# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RunRRR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SWXMLHash'
  pod 'ALCameraViewController'
  pod 'SwiftyCam'
  # Pods for RunRRR

end
